### ISSUE TITLE
List of filters

### ISSUE THREAD

**Issue by Luferov** [devind-team/graphene-django-filter#18]
May add list of exists filters ('exact', 'contains',...) in documentation?

**Comment by SquakR** [comment]
I think there is not necessary because the library currently doesn't interfere in Filters generation and uses the same Filters as django-filters does. Django-filter specifies a link to Django docs. Maybe it is reasonable specify to this link in our documentation and the fact that the library doesn't change lookup expressions.  
![image](https://user-images.githubusercontent.com/66582102/156337894-911a5a6e-6e95-4268-8da6-6f6db06c0f21.png)
